---
title: C28125 | Microsoft Docs
ms.custom: ''
ms.date: 2018-06-30
ms.prod: visual-studio-dev14
ms.reviewer: ''
ms.suite: ''
ms.technology:
- vs-devops-test
ms.tgt_pltfrm: ''
ms.topic: article
f1_keywords:
- C28125
helpviewer_keywords:
- C28125
ms.assetid: 3f7b8db4-6a64-4480-919e-3f3ceca7f948
caps.latest.revision: 6
author: corob-msft
ms.author: gewarren
manager: ghogen
ms.openlocfilehash: 96aeeed083375c5432eab3637d1131369742f75a
ms.sourcegitcommit: 55f7ce2d5d2e458e35c45787f1935b237ee5c9f8
ms.translationtype: MT
ms.contentlocale: pt-BR
ms.lasthandoff: 08/22/2018
ms.locfileid: "47461475"
---
# <a name="c28125"></a>C28125
[!INCLUDE[vs2017banner](../includes/vs2017banner.md)]

A versão mais recente deste tópico pode ser encontrada em [C28125](https://docs.microsoft.com/visualstudio/code-quality/c28125).  
  
Aviso C28125: A função deve ser chamada de dentro de um bloco try / except bloco  
  
 O driver está chamando uma função que deve ser chamada de dentro de um bloco try / except bloco, tais como [ProbeForRead](http://msdn.microsoft.com/library/windows/hardware/ff559876.aspx), [ProbeForWrite](http://msdn.microsoft.com/library/windows/hardware/ff559879.aspx), [MmProbeAndLockPages](http://msdn.microsoft.com/library/windows/hardware/ff554664.aspx).  
  
## <a name="example"></a>Exemplo  
 O exemplo de código a seguir gera este aviso:  
  
```  
ProbeForRead(addr, len, 4);  
```  
  
 O exemplo de código a seguir evita este aviso:  
  
```  
  
__try  
{  
    ProbeForRead(addr, len, 4);  
}  
__except(EXCEPTION_EXECUTE_HANDLER)  
{  
    Status = GetExceptionCode();  
    ... report error status  
}  
```



