---
title: C26111 | Microsoft Docs
ms.custom: 
ms.date: 11/04/2016
ms.reviewer: 
ms.suite: 
ms.technology: vs-ide-code-analysis
ms.tgt_pltfrm: 
ms.topic: article
f1_keywords: C26111
helpviewer_keywords: C26111
ms.assetid: 85fc740a-3bbb-41b8-a848-95e243a08da9
caps.latest.revision: "8"
author: mikeblome
ms.author: mblome
manager: ghogen
ms.workload: multiple
ms.openlocfilehash: dadc0c15e07595d3a35d4cb4a92f257bdcdf3490
ms.sourcegitcommit: 32f1a690fc445f9586d53698fc82c7debd784eeb
ms.translationtype: MT
ms.contentlocale: pt-BR
ms.lasthandoff: 12/22/2017
---
# <a name="c26111"></a>C26111
Aviso C26111: Falha ao liberar o bloqueio de chamador \<bloqueio > antes de chamar a função \<func >.  
  
 A anotação `_Requires_lock_not_held_` impõe uma pré-condição que a contagem de bloqueio para o bloqueio especificado não pode ser maior que zero quando a função é chamada. C26111 de aviso será emitido quando uma função falha ao liberar o bloqueio antes de chamar outra função.  
  
## <a name="example"></a>Exemplo  
 O exemplo a seguir gera o aviso C26111 porque o `_Requires_lock_not_held_` pré-condição for violada pela chamada para `DoNotLock` dentro da seção bloqueada.  
  
```  
  
typedef struct _DATA   
{  
    CRITICAL_SECTION cs;  
    int d;  
} DATA;  
  
_Requires_lock_not_held_(p->cs)   
  
void DoNotLock(DATA* p)  
{  
    EnterCriticalSection(&p->cs);   
    p->d = 0;  
    LeaveCriticalSection(&p->cs);  
}  
  
void LockedFunction(DATA* p)   
{   
    EnterCriticalSection(&p->cs);   
    DoNotLock(p); // Warning C26111  
    LeaveCriticalSection(&p->cs);  
}  
  
```