---
title: "C28105 | Microsoft Docs"
ms.custom: ""
ms.date: "12/03/2016"
ms.prod: "visual-studio-dev14"
ms.reviewer: ""
ms.suite: ""
ms.technology: 
  - "vs-devops-test"
ms.tgt_pltfrm: ""
ms.topic: "article"
f1_keywords: 
  - "C28105"
helpviewer_keywords: 
  - "C28105"
ms.assetid: 5afdec78-30eb-470c-980f-93d0cb3e74cc
caps.latest.revision: 3
caps.handback.revision: 3
author: "corob-msft"
ms.author: "corob"
manager: "ghogen"
---
# C28105
[!INCLUDE[vs2017banner](../code-quality/includes/vs2017banner.md)]

C28105 de aviso: Recurso de escape devido a uma exceção  
  
 O recurso especificado não é liberado quando uma exceção é gerada.  A instrução especificada pelo caminho pode gerar uma exceção.  Esse aviso é semelhante a um aviso [C28103](../code-quality/c28103.md), exceto que nesse caso uma exceção é envolvida.  
  
## Exemplo  
 O exemplo de código gerenciado esse aviso:  
  
```  
res = KeSaveFloatingPointState(buffer);  
  
res = AllocateResource(Resource);  
char *p2 = new char[10]; // could throw  
  
delete[] p2;  
FreeResource(Resource)  
```  
  
 O exemplo de código a seguir evita esse aviso:  
  
```  
res = AllocateResource(Resource);  
char *p2;  
  
try {  
    p2 = new char[10];  
} catch (std::bad_alloc *e) {  
    // just handle the throw  
    ;  
}  
FreeResource(Resource)  
```