---
title: C28198 | Microsoft Docs
ms.custom: 
ms.date: 11/04/2016
ms.reviewer: 
ms.suite: 
ms.technology:
- vs-ide-code-analysis
ms.tgt_pltfrm: 
ms.topic: article
f1_keywords:
- C28198
helpviewer_keywords:
- C28198
ms.assetid: 8bad4acb-712c-43f5-81d1-45d92092d4c5
caps.latest.revision: 
author: mikeblome
ms.author: mblome
manager: ghogen
ms.workload:
- multiple
ms.openlocfilehash: a930019b1f7369f1d6035eef4f467d0fe17c6732
ms.sourcegitcommit: 32f1a690fc445f9586d53698fc82c7debd784eeb
ms.translationtype: MT
ms.contentlocale: pt-BR
ms.lasthandoff: 12/22/2017
---
# <a name="c28198"></a>C28198
Aviso C28198: possivelmente vazando memória devido a uma exceção.  
  
 Esse aviso indica que a memória alocada não está sendo liberado após uma exceção é gerada. A instrução no final do caminho pode gerar uma exceção. A memória foi passada para uma função que possam ter salvo uma cópia a ser liberada posteriormente.  
  
 Esse aviso é muito semelhante ao aviso [C28197](../code-quality/c28197.md). As anotações que são recomendadas para uso com o aviso [C28197](../code-quality/c28197.md) também podem ser usados aqui.  
  
## <a name="example"></a>Exemplo  
 O exemplo de código a seguir gera este aviso:  
  
```  
char *p1 = new char[10];  
char *p2 = new char[10];  
  
test(p1);   // does not save a copy of p  
  
delete[] p2;  
delete[] p1;  
```  
  
 O exemplo de código a seguir evita este aviso:  
  
```  
char *p1 = new char[10];  
char *p2 = NULL;  
  
test(p1);   // does not save a copy of p  
try {  
    p2 = new char[10];  
} catch (std::bad_alloc *e) {  
    // just handle the throw  
    ;  
}  
```