---
title: C6255 | Microsoft Docs
ms.custom: ''
ms.date: 11/04/2016
ms.technology:
- vs-ide-code-analysis
ms.topic: conceptual
f1_keywords:
- C6255
helpviewer_keywords:
- C6255
ms.assetid: bb6430b2-782a-4410-a8e1-609df06007de
author: mikeblome
ms.author: mblome
manager: douge
ms.workload:
- multiple
ms.openlocfilehash: e9374b6c0a8d1ede3c0b7fe6d3ef01e71c2715fb
ms.sourcegitcommit: 6a9d5bd75e50947659fd6c837111a6a547884e2a
ms.translationtype: MT
ms.contentlocale: pt-BR
ms.lasthandoff: 04/16/2018
---
# <a name="c6255"></a>C6255
Aviso C6255: alloca indicou falha, gerando uma exceção de estouro de pilha. Considere utilizar malloca em vez disso  
  
 Esse aviso indica que uma chamada para `_alloca` detectou fora de tratamento de exceção local. `_alloca` deve sempre ser chamado de dentro do intervalo de um manipulador de exceção protegido porque ele pode gerar uma exceção de estouro de pilha em caso de falha. Se possível, em vez de usar `_alloca`, considere o uso de `_malloca` que é uma versão mais segura do `_alloca`.  
  
## <a name="example"></a>Exemplo  
 O código a seguir gera este aviso porque `_alloca` pode gerar exceção:  
  
```  
#include <windows.h>  
  
void f( )  
{  
  void *p = _alloca(10);  
  // code ...  
}  
  
```  
  
 Para corrigir esse aviso, use `_malloca` e adicione o manipulador de exceção conforme mostrado no código a seguir:  
  
```  
#include <windows.h>  
#include <malloc.h>  
  
void f( )  
{  
  void *p;  
  int errcode;  
  __try   
  {  
    p = _malloca(10);  
    // code...  
    _freea(p);  
  }  
  __except( (GetExceptionCode() == STATUS_STACK_OVERFLOW ) ?  
              EXCEPTION_EXECUTE_HANDLER : EXCEPTION_CONTINUE_SEARCH )  
  {  
    errcode = _resetstkoflw();  
    // code ...  
  }  
}  
```  
  
## <a name="see-also"></a>Consulte também  
 [_malloca](/cpp/c-runtime-library/reference/malloca)