---
title: C6318 | Microsoft Docs
ms.custom: 
ms.date: 11/04/2016
ms.reviewer: 
ms.suite: 
ms.technology: vs-ide-code-analysis
ms.tgt_pltfrm: 
ms.topic: article
f1_keywords: C6318
helpviewer_keywords: C6318
ms.assetid: 3284a83e-bb8e-461c-adcc-cfc66ceea05e
caps.latest.revision: "13"
author: mikeblome
ms.author: mblome
manager: ghogen
ms.openlocfilehash: 665306542042675380ad5a9d7b0294d8b1722e60
ms.sourcegitcommit: fb751e41929f031d1a9247bc7c8727312539ad35
ms.translationtype: MT
ms.contentlocale: pt-BR
ms.lasthandoff: 11/15/2017
---
# <a name="c6318"></a>C6318
Aviso C6318: Try bem-definido /\__except: uso de EXCEPTION_CONTINUE_SEARCH constante ou outra constante que é avaliada como zero na expressão de filtro de exceção. O código no bloco do manipulador de exceção não é executado  
  
 Esse aviso indica que se ocorrer uma exceção no bloco protegido deste manipulador de exceção estruturada, a exceção não será manipulada porque a constante `EXCECPTION_CONTINUE_SEARCH` é usado na expressão de filtro de exceção.  
  
 Esse código é equivalente ao bloco protegido sem o bloco do manipulador de exceção porque o bloco do manipulador não é executado.  
  
## <a name="example"></a>Exemplo  
 O código a seguir gera este aviso:  
  
```  
#include <excpt.h>  
#include <stdio.h>  
  
void f (char *pch)  
{  
  __try   
  {  
    // assignment might fail  
    *pch = 0;  
  }   
  __except (EXCEPTION_CONTINUE_SEARCH) // warning 6318  
  {  
    puts("Exception Occurred");  
  }  
}  
```  
  
 Para corrigir esse aviso, use o seguinte código:  
  
```  
#include <excpt.h>  
#include <stdio.h>  
#include <windows.h>  
  
void f (char *pch)  
{  
  __try   
  {  
    // assignment might fail  
    *pch = 0;  
  }   
  __except( (GetExceptionCode() == EXCEPTION_ACCESS_VIOLATION) ?  
                EXCEPTION_EXECUTE_HANDLER : EXCEPTION_CONTINUE_SEARCH )  
  {  
    puts("Access violation");  
  }  
}   
```  
  
## <a name="see-also"></a>Consulte também  
 [Instrução try-except](/cpp/cpp/try-except-statement)